name: Deploy Mendeszap - S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.21.0
      - name: INSTALL AWS CLIENT
        run: pip install awscli
      - name: INSTALL E BUILD
        run: npm install && npm run build
        env:
           CI: "false" 
      - name: DEPLOY S3
        run: cd build && AWS_ACCESS_KEY_ID=AKIAZ2VZKZ23H7IUFWAP AWS_SECRET_ACCESS_KEY=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 aws s3 sync . s3://mendeszap --acl public-read --delete 
